# Looks
foreground         #cdd6f4
background         #1e1e2e
cursor             #cdd6f4

active_tab_foreground     #1e1e2e
active_tab_background     #cdd6f4
inactive_tab_foreground   #cdd6f4
inactive_tab_background   #1e1e2e

active_border_color   #cdd6f4
inactive_border_color #6c7086
bell_border_color     #f38ba8

color0       #1e1e2e
color8       #6c7086
color1       #f38ba8
color9       #eba0ac
color2       #a6e3a1
color10      #94e2d5
color3       #fab387
color11      #f9e2af
color4       #89b4fa
color12      #b4befe
color5       #cba6f7
color13      #f5c2e7
color6       #74c7ec
color14      #89dceb
color7       #bac2de
color15      #cdd6f4

# Fonts:
font_family     ProFont IIx Nerd Font Mono
font_size 11.5

# Cursor:
cursor_shape block
shell_integration no-cursor
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
touch_scroll_multiplier 4

enable_audio_bell no

# Layout:
enabled_layouts splits
map alt+s launch --location=hsplit
map alt+v launch --location=vsplit

map alt+shift+k move_window up
map alt+shift+h move_window left
map alt+shift+l move_window right
map alt+shift+j move_window down

map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

# Window:
window_padding_width 16
confirm_os_window_close 0

# Misc
shell .
allow_remote_control yes
tab_bar_style powerline

# Other binds
map alt+shift+u scroll_page_up
map alt+shift+d scroll_page_down
map alt+t new_tab
map alt+n next_tab
map alt+p previous_tab
map alt+c close_window
map alt+shift+c close_tab

