#!/usr/bin/env bash

animate() {
    local frame_duration="${1}"
    shift

    local frames=( "$@" )
    local now_us="${EPOCHREALTIME/./}"
    local frame=$(( (now_us / frame_duration) % ${#frames[@]} ))

    printf '%s' "${frames[frame]}"
}
music() {
    local action="$1"
    local value="$2"
    case "$action" in 
        "togglepause") 
            rmpc togglepause
            ;;
        "next") 
            rmpc next
            ;;
        "prev") 
            rmpc prev
            ;;
        "togglerepeat") 
            rmpc togglerepeat
            ;;
        "togglerandom") 
            rmpc togglerandom
            ;;
        "togglesingle") 
            rmpc togglesingle
            ;;
        "toggleconsume") 
            rmpc toggleconsume
            ;;
        "seek")
            rmpc seek "$value"
            ;;
    esac
}
bt(){
    local action="$1"
    local bool="$2"
    local device="$3"
    case "$action" in 
        "power") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl power on 
            else 
                bluetoothctl power off
            fi
            ;;
        "discoverable") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl discoverable on 
            else 
                bluetoothctl discoverable off
            fi
            ;;
        "pairable") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl pairable on 
            else 
                bluetoothctl pairable off
            fi
            ;;
        "pair") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl pair "$device" 
            else 
                bluetoothctl pair "$device"
            fi
            ;;
        "trust") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl trust "$device" 
            else 
                bluetoothctl untrust "$device"
            fi
            ;;
        "block") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl block "$device" 
            else 
                bluetoothctl unblock "$device"
            fi
            ;;
        "connect") 
            if [[ "$bool" == "no" ]] ; then 
                bluetoothctl connect "$device" 
            else 
                bluetoothctl disconnect "$device"
            fi
            ;;
        "remove") 
            if [[ "$bool" == "yes" ]] ; then 
                bluetoothctl remove "$device" 
            fi
            ;;
    esac
}
audio(){
    local action="$1"
    local node="$2"
    local value="$3"
    case "$action" in 
        "set_volume") 
            if [[ "$node" == "sink" ]] ; then 
                wpctl set-volume @DEFAULT_SINK@ "$value"%
            elif [[ "$node" == "source" ]] ; then
                wpctl set-volume @DEFAULT_SOURCE@ "$value"%
            fi
            ;;
    esac
}
 case "$1" in
     "animate") shift ; animate "$@" ; exit 0 ;;
     "music") shift ; music "$@" ; exit 0 ;;
     "audio") shift ; audio "$@" ; exit 0 ;;
     "bt") shift ; bt "$@" ; exit 0 ;;
     *) exit 1 ;; 
 esac

