#!/usr/bin/env bash

trim() {
    local var="$1"
    local trimmed
    trimmed="${var#"${var%%[![:space:]]*}"}"
    trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"
    printf '%s' "$trimmed"
}
normalize_spaces() {
    local str="$*"
    # dont qoute, we need the word splitting
    # bash excludes the spaces and takes only 
    # the words as arguments
    set -- $str
    printf '%s' "$*"
}
setup_cache_dir() {
    CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/ZAPP"
    mkdir -p "$CACHE_DIR"
}

scroll_text() {
    local text="$1"
    local width="$2"
    local len=${#text}

    if (( len <= width )); then
        printf "%s" "$text"
        return
    fi

    local spacer="   "
    local scroll="$text$spacer"

    local sec
    sec="$(date "+%s" 2> /dev/null)" 
    [[ "$sec" == '' ]] && sec=0

    local i="$((sec % ${#scroll}))"

    local part="${scroll:i:width}"
    if (( ${#part} < width )); then
        part+="${scroll:0:width-${#part}}"
    fi
    printf "%s" "${part}"
}

# GPU {{{

declare -A gpu_arr # pcie_bus_id:name
declare -A gpu_temp_arr # pcie_bus_id:centigrade
declare -A gpu_usage_arr # pcie_bus_id:percent
declare -A total_vram_arr # MiB
declare -A vram_usage_arr # MiB

declare can_get_gpu
declare -a nvidia_gpus
declare -a intel_gpus
declare has_NVIDIA=false
declare has_Intel=false

init_gpu(){
    if ! [[ -x $(which lspci 2> /dev/null) ]] ; then
        can_get_gpu=false
    else
        can_get_gpu=true
    fi
}
get_gpu() {
    local gpu_command="lspci -mm"
    declare -A gpu_raw
    while IFS='"' read -ra parts ; do
        if [[ "${parts[1]}" == +(VGA*|Display*|3D*) ]] ; then
            
            gpu_raw["$( trim "${parts[0]}")"]="${parts[3]} ${parts[5]}"
        fi
    done < <( $gpu_command )
    for key in "${!gpu_raw[@]}" ; do
        case "${gpu_raw[$key]}" in
            *"Advanced"*)
                brand="${gpu_raw[$key]/*AMD*ATI*/AMD ATI}"
                brand="${brand:-${gpu_raw[$key]/*AMD*/AMD}}"
                brand="${brand:-${gpu_raw[$key]/*ATI*/ATi}}"

                gpu_raw[$key]="${gpu_raw[$key]/\[AMD\/ATI\] }"
                gpu_raw[$key]="${gpu_raw[$key]/\[AMD\] }"
                gpu_raw[$key]="${gpu_raw[$key]/OEM }"
                gpu_raw[$key]="${gpu_raw[$key]/Advanced Micro Devices, Inc.}"
                gpu_raw[$key]="${gpu_raw[$key]/*\[}"
                gpu_raw[$key]="${gpu_raw[$key]/\]*}"
                gpu_raw[$key]="$brand ${gpu_raw[$key]}"
            ;;

            *"NVIDIA"*)
                gpu_raw[$key]="${gpu_raw[$key]/*\[}"
                gpu_raw[$key]="${gpu_raw[$key]/\]*}"
                gpu_raw[$key]="NVIDIA ${gpu_raw[$key]}"
            ;;

            *"Intel"*)
                gpu_raw[$key]="${gpu_raw[$key]/*Intel/Intel}"
                gpu_raw[$key]="${gpu_raw[$key]/\(R\)}"
                gpu_raw[$key]="${gpu_raw[$key]/Corporation}"
                gpu_raw[$key]="${gpu_raw[$key]/ \(*}"
                gpu_raw[$key]="${gpu_raw[$key]/Integrated Graphics Controller}"
                gpu_raw[$key]="${gpu_raw[$key]/*Xeon*/Intel HD Graphics}"
            ;;

            *"MCST"*)
                gpu_raw[$key]="${gpu_raw[$key]/*MCST*MGA2*/MCST MGA2}"
            ;;

            *"VirtualBox"*)
                gpu_raw[$key]="VirtualBox Graphics Adapter"
            ;;

            *) return ;;
        esac
        gpu_arr[$key]="$(normalize_spaces "${gpu_raw[$key]}")"
    done
}
init_gpu_dynamic(){
    # Super sketchy need better ways -------------------------
    for bus_id in "${!gpu_arr[@]}" ; do 
        if [[ "${gpu_arr[$bus_id]}" == NVIDIA* ]] ; then 
            nvidia_gpus+=( "$bus_id" )
        elif [[ "${gpu_arr[$bus_id]}" == Intel* ]] ; then 
            intel_gpus+=( "$bus_id" )
        fi
    done
    # --------------------------------------------------------
    if [[ -n "${nvidia_gpus[*]}" ]] ; then
        if ! [[ -x $(which nvidia-smi  2> /dev/null) ]] ; then
            return 1
        else
            has_NVIDIA=true
        fi
    fi
    if [[ -n "${intel_gpus[*]}" ]] ; then
        if ! [[ -x $(which intel_gpu_top  2> /dev/null) ]] ; then
            return 1
        else
            if ! [[ "$(getcap "$(which intel_gpu_top)")" == *cap_perfmon=ep* ]]
            then
                return 1
            else
                has_Intel=true
            fi
        fi
    fi
}
get_gpu_dynamic() {
    local interval="${1:-1}"

    NVIDIA() {
        # pcie_bus_id: It's the location of the device on the PCI/PCIe bus 
        #              hierarchy
        # format:      domain:bus:device.function
        # Domain:      The PCI domain separates completely independent PCI 
        #              hierarchies. Most consumer systems have only one domain
        # Bus:         The CPU/root complex starts with bus 00, then PCI bridges 
        #              create new buses.
        # Device:      Each bus can have 32 devices:
        # Function:    Each device can have up to 8 functions:
        local pcie_bus_id util mem_used total_mem temp
        while IFS=, read -r pcie_bus_id util mem_used total_mem temp ; do 
            # -----------------------------
            pcie_bus_id="${pcie_bus_id#*:}"
            pcie_bus_id="$(trim "$pcie_bus_id")"
            # -----------------------------
            util="$(trim "$util")"
            gpu_usage_arr["$pcie_bus_id"]="$util"
            # -----------------------------
            mem_used="$(trim "$mem_used")"
            vram_usage_arr["$pcie_bus_id"]="$mem_used"
            # -----------------------------
            total_mem="$(trim "$total_mem")"
            total_vram_arr["$pcie_bus_id"]="$total_mem"
            # -----------------------------
            temp="$(trim "$temp")"
            gpu_temp_arr["$pcie_bus_id"]="$temp"
            # -----------------------------
        done < <(nvidia-smi \
--query-gpu=pci.bus_id,utilization.gpu,memory.used,memory.total,temperature.gpu \
            --format=csv,noheader,nounits)
    }
    
    INTEL() {
        local Freq_req RCS 

        for pcie_bus_id in "${intel_gpus[@]}"; do
            while IFS=, read -r Freq_req _ _ _ \
                _ _ RCS rest; do
                
                # Intel GPUs have different hardware engines, 
                # each doing different tasks. 
                # RCS: Usage of the main 3D rendering engine.
                # BCS: Blitter Copy Engine
                # VCS: Video Codec Engine
                # VECS: Video Enhancement Engine

                [[ "$Freq_req" == "Freq MHz req" ]] && continue

                gpu_usage_arr["$pcie_bus_id"]="${RCS/.*}"

            done < <(
                intel_gpu_top -c -n 1 -s "$((interval * 500))" -d \
                    "sys:/sys/devices/pci0000:00/0000:$pcie_bus_id" )
        done
    }
    
    $has_NVIDIA && NVIDIA
    $has_Intel && INTEL
}
get_gpu_main() {
    init_gpu
    $can_get_gpu || return 1

    get_gpu
    init_gpu_dynamic
    get_gpu_dynamic

    local out='{"gpu":[]}'

    for pcie_bus_id in "${!gpu_arr[@]}"; do
        out="$(
            jq \
                --arg name "${gpu_arr[$pcie_bus_id]}" \
                --arg temp "${gpu_temp_arr[$pcie_bus_id]}" \
                --arg usage "${gpu_usage_arr[$pcie_bus_id]}" \
                --arg vram_total "${total_vram_arr[$pcie_bus_id]}" \
                --arg vram_usage "${vram_usage_arr[$pcie_bus_id]}" \
                '
                .gpu += [{
                    name: $name,
                    temp: $temp,
                    usage: $usage,
                    vram_total: $vram_total,
                    vram_usage: $vram_usage
                }]
                ' <<< "$out"
        )"
    done

    printf '%s' "$out"
}
# }}}

# DISK {{{
disk_stats() {
    local interval="${1:-1}"

    local before='{"disk":{}}'
    local after='{"disk":{}}'

    while read -r _ _ name \
        reads_completed _ sectors_read _ \
        writes_completed _ sectors_written _ \
        rest
    do
        before="$(
            jq \
                --arg dev "$name" \
                --argjson reads "$reads_completed" \
                --argjson writes "$writes_completed" \
                --argjson sectors_read "$sectors_read" \
                --argjson sectors_written "$sectors_written" \
                '
                .disk[$dev] = {
                    reads: $reads,
                    writes: $writes,
                    sectors_read: $sectors_read,
                    sectors_written: $sectors_written
                }
                ' <<< "$before"
        )"
    done < /proc/diskstats

    sleep "$interval"

    while read -r _ _ name \
        reads_completed _ sectors_read _ \
        writes_completed _ sectors_written _ \
        rest
    do
        after="$(
            jq \
                --arg dev "$name" \
                --argjson reads "$reads_completed" \
                --argjson writes "$writes_completed" \
                --argjson sectors_read "$sectors_read" \
                --argjson sectors_written "$sectors_written" \
                '
                .disk[$dev] = {
                    reads: $reads,
                    writes: $writes,
                    sectors_read: $sectors_read,
                    sectors_written: $sectors_written
                }
                ' <<< "$after"
        )"
    done < /proc/diskstats

    jq -n \
        --argjson before "$before" \
        --argjson after "$after" \
        --argjson interval "$interval" '
        {
            disk: [
                ($after.disk | keys[] as $dev |
                    {
                        device: $dev,

                        read_kibps:
                            ((($after.disk[$dev].sectors_read
                             - $before.disk[$dev].sectors_read)
                             / 2) / $interval | floor),

                        write_kibps:
                            ((($after.disk[$dev].sectors_written
                             - $before.disk[$dev].sectors_written)
                             / 2) / $interval | floor),

                        total_kibps:
                            (((($after.disk[$dev].sectors_read
                              - $before.disk[$dev].sectors_read)
                             +
                              ($after.disk[$dev].sectors_written
                              - $before.disk[$dev].sectors_written))
                             / 2) / $interval | floor),

                        read_iops:
                            (($after.disk[$dev].reads
                             - $before.disk[$dev].reads)
                             / $interval | floor),

                        write_iops:
                            (($after.disk[$dev].writes
                             - $before.disk[$dev].writes)
                             / $interval | floor)
                    }
                )
            ]
        }
        '
}
# }}}

# AUDIO {{{
fetch_music () {
    command -v rmpc &> /dev/null || return 1
    local albumart_file="$CACHE_DIR/albumart"
    local MAX_CHAR=15

    music_info_json="$(rmpc song 2> /dev/null)"
    [[ "$music_info_json" == "" ]] && { printf '{}' ; return 1 ; }
    local status_info
    status_info="$(rmpc status 2> /dev/null)"
    [[ "$status_info" == "" ]] && { printf '{}' ; return 1 ; }
    music_info_json=$(jq --argjson status "$status_info" \
            '. += $status' <<< "$music_info_json" )
    rmpc albumart -o "$albumart_file" &> /dev/null
    if [[ -f "$albumart_file" ]] ; then 
        music_info_json=$(jq --arg albumart "$albumart_file" \
            '.albumart = $albumart' <<< "$music_info_json" )
    fi
    local title="$(jq -r '.metadata.title' <<< "$music_info_json" 2> /dev/null)"
    local artist="$(jq -r \
        '.metadata.artist | (. | if type == "array" then . else [.] end)[]' \
        <<< "$music_info_json" 2> /dev/null)"
    artist="${artist//$'\n'/','}"

    if [[ "$title" ]] ; then 
        local scroll_title="$(scroll_text "$title" "$MAX_CHAR")" 
        music_info_json=$(jq --arg scroll_title "$scroll_title" \
            '.scroll_title = $scroll_title' <<< "$music_info_json" )
    fi
    if [[ "$artist" ]] ; then 
        local scroll_artist="$(scroll_text "$artist" "$MAX_CHAR")" 
        music_info_json=$(jq --arg scroll_artist "$scroll_artist" \
            '.scroll_artist = $scroll_artist' <<< "$music_info_json" )
    fi
    jq -n --argjson music_info_json "$music_info_json" \
      '{"music":$music_info_json}'

}
# }}}

# VOLUME {{{
fetch_volume() {
    read -r _volume VOL_SINK IS_MUTE_SINK \
        < <( wpctl get-volume @DEFAULT_SINK@ 2> /dev/null || printf '"null"' )
    read -r _volume VOL_SOURCE IS_MUTE_SOURCE \
        < <( wpctl get-volume @DEFAULT_SOURCE@ 2> /dev/null || printf '"null"' )
    [[ "$IS_MUTE_SINK" == '' ]] && IS_MUTE_SINK=false || IS_MUTE_SINK=true
    [[ "$IS_MUTE_SOURCE" == '' ]] && IS_MUTE_SOURCE=false || IS_MUTE_SOURCE=true
    [[ "$VOL_SINK" == '"null"' ]] && IS_MUTE_SINK='"null"'
    [[ "$VOL_SOURCE" == '"null"' ]] && IS_MUTE_SOURCE='"null"'

    jq -n \
        --argjson vol_sink "$VOL_SINK" \
        --argjson vol_source "$VOL_SOURCE" \
        --argjson is_mute_sink "$IS_MUTE_SINK" \
        --argjson is_mute_source "$IS_MUTE_SOURCE" \
        '{
            "volume":
            {
                "vol_sink":$vol_sink,
                "vol_source":$vol_source,
                "is_mute_sink":$is_mute_sink,
                "is_mute_source":$is_mute_source
            }
        }'
}
# }}}

# NETWORK {{{
fetch_network(){
    command -v ip &> /dev/null || { printf '[]' ; return 1 ; }
    declare -A net_dev_state  # dev:state
    declare -A net_link_state  # dev:link_state
    declare -A net_ip_addr # dev:ip ...
    declare -A net_gate # dev:dest-gateway ...
    declare -A net_up_speed # dev:bytes
    declare -A net_down_speed #dev:bytes
    local interval=1
    # Link layer
    local link_out_start="$( ip -o -s link )"
    sleep "$interval"
    local link_out_end="$( ip -o -s link )"
    declare -A down_speed_start
    declare -A down_speed_end
    declare -A up_speed_start
    declare -A up_speed_end
    local idx dev dev_info mtu mtu_v q_d q_d_v link_state link_state_v rest
    while read -r idx dev dev_info mtu mtu_v q_d q_d_v link_state link_state_v \
        rest ; do
        local dev=${dev%%:}
        if ! [[ "$dev" == lo ]] ; then
            if [[ "$dev_info" == *UP* ]] ; then
                local dev_state="UP"
            else
                local dev_state="DOWN"
            fi
            net_dev_state["$dev"]="$dev_state"
            net_link_state["$dev"]="$link_state_v"
            if [[ "$link_state_v" == "UP" ]] ; then
                while read -ra arr ; do
                    for idx in "${!arr[@]}" ; do
                        if [[ "${arr[$idx]}" == "RX:" ]] ; then
                            down_speed_start["$dev"]="${arr[$(( idx + 8 ))]}"
                        fi
                        if [[ "${arr[$idx]}" == "TX:" ]] ; then
                            up_speed_start["$dev"]="${arr[$(( idx + 8 ))]}"
                        fi
                    done
                done <<< "$rest"
            fi
        fi
    done <<< "$link_out_start"
    while read -r idx dev dev_info mtu mtu_v q_d q_d_v link_state link_state_v \
        rest ; do
        local dev=${dev%%:}
        if ! [[ "$dev" == lo ]] ; then
            if [[ "$link_state_v" == "UP" ]] ; then
                while read -ra arr ; do
                    for idx in "${!arr[@]}" ; do
                        if [[ "${arr[$idx]}" == "RX:" ]] ; then
                            down_speed_end["$dev"]="${arr[$(( idx + 8 ))]}"
                        fi
                        if [[ "${arr[$idx]}" == "TX:" ]] ; then
                            up_speed_end["$dev"]="${arr[$(( idx + 8 ))]}"
                        fi
                    done
                done <<< "$rest"
            fi
        fi
    done <<< "$link_out_end"
    for dev in "${!down_speed_start[@]}" ;  do
        net_down_speed["$dev"]="$(( ( ${down_speed_end[$dev]} - \
            ${down_speed_start[$dev]}) / interval ))"
        net_up_speed["$dev"]="$(( ( ${up_speed_end[$dev]} - \
            ${up_speed_start[$dev]}) / interval ))"
    done
    # Network Layer
    net_ip_addr=()
    local inet ip
    while read -r idx dev inet ip rest ; do
        for d in "${!net_dev_state[@]}" ; do
            if [[ "$dev" == "$d" ]] ; then
                if [[ "$ip" == +([[:digit:]./]) ]] ; then
                    net_ip_addr["$dev"]+="$ip "
                fi
            fi
        done
    done <  <(ip -o addr)
    # -----------------
    net_gate=()
    local dest via gate dev_v
    while read -r dest via gate dev dev_v rest ; do
        for d in "${!net_dev_state[@]}" ; do
            if [[ "$dev_v" == "$d" ]] ; then
                if [[ "$dest" == "default" ]]  ; then
                    dest="0.0.0.0"
                fi
                if [[ "$gate" == +([[:digit:]./]) ]] ; then
                    net_gate["$dev_v"]+="$dest-$gate "
                fi
            fi
        done
    done < <(ip -o route)
    # -----------------

    declare -a dev_order_link_state
    declare -a dev_order_down_speed

    # sorting based of link state
    for dev in "${!net_link_state[@]}" ; do 
        [[ "${net_link_state[$dev]}" == "UP" ]] && \
            dev_order_link_state+=("$dev")
    done
    # sorting based on down speed
    local down_speed=0
    local idx=999
    for dev in "${dev_order_link_state[@]}" ; do 
        if [[ "${net_down_speed["$dev"]}" -ge $down_speed ]] ; then
            down_speed="${net_down_speed["$dev"]}"
            dev_order_down_speed[idx]="$dev"
        fi
    done
    # -------------------------------------------
    for dev in "${!net_link_state[@]}" ; do 
        [[ "${net_link_state[$dev]}" == "DOWN" ]] && \
            dev_order_down_speed+=("$dev")
    done

    # construct json output
    local net_json_out="[]"

    # single-valued-keys
    for dev in "${dev_order_down_speed[@]}" ; do
        [[ "${net_down_speed["$dev"]}" ]] || net_down_speed["$dev"]="0"
        [[ "${net_up_speed["$dev"]}" ]] || net_up_speed["$dev"]="0"
        net_json_out=$(printf '%s' "$net_json_out" \
            | jq  --arg dev "$dev" \
            --arg state "${net_dev_state["$dev"]}" \
            --arg link_state "${net_link_state["$dev"]}" \
            --arg net_down_speed "${net_down_speed["$dev"]}" \
            --arg net_up_speed "${net_up_speed["$dev"]}" \
            '. += [{"dev":$dev,"state":$state,
        "link_state":$link_state,"net_down_speed":$net_down_speed,
        "net_up_speed":$net_up_speed}]') 
    done
    # array-valued-keys
    for dev in "${dev_order_down_speed[@]}" ; do
        while IFS= read -r -d ' ' ip_addr ; do 
            net_json_out=$(printf '%s' "$net_json_out" \
                | jq \
                --arg dev "$dev" \
                --arg ip_addr "$ip_addr" \
                'map(if .dev == $dev then ."ip_addr" += [$ip_addr] else ."ip_addr" += ["null"] end)') 
        done <<< "${net_ip_addr["$dev"]}"
    done
    for dev in "${dev_order_down_speed[@]}" ; do
        while IFS= read -r -d ' ' gate ; do 
            while IFS='-' read -r dest via ; do
                net_json_out=$(printf '%s' "$net_json_out" \
                    | jq \
                    --arg dev "$dev" \
                    --arg dest "$dest" \
                    --arg via "$via" \
                    'map(if .dev == $dev then ."gate" += [[$dest,$via]] else ."gate" += [["null","null"]] end)') 
            done <<< "$gate"
        done <<< "${net_gate["$dev"]}"
    done

    jq -n --argjson net_json_out "$net_json_out" \
      '{"net":$net_json_out}' 2> /dev/null || printf '{"net":[]}'
}
# }}}

# BLUETOOTH {{{
fetch_bluetooth(){
    local bluetooth_info_json="{}"
    command -v bluetoothctl &> /dev/null \
        || { printf '%s' "$bluetooth_info_json" ; return 1 ; }
    
    # controller info
    # ---------------
    local ctrl mac alias default
    while read -r ctrl mac alias default ; do 
        local is_default="no"
        [[ "$default" == "[default]" ]] && is_default="yes"
        bluetooth_info_json="$(jq \
            --arg mac "$mac" \
            --arg alias "$alias" \
            --arg is_default "$is_default" \
            '.controllers += 
            [{"mac_addr":$mac,"alias":$alias,"is_default":$is_default}]' \
            <<< "$bluetooth_info_json" )"
    done < <( bluetoothctl list )
    
    # jq outputs valid json with quotes and stuff, we dont want that. use -r 
    for ctrl in $(jq -r '.controllers[].mac_addr' <<< "$bluetooth_info_json") ; do 
        local key value
        while read -r key value ; do 
            case "$key" in 
                # |= acts exactly like a pipe, but just modifies the data instead
                # of a fully filtered output.
                "Powered:") \
                    bluetooth_info_json=$(jq \
                    --arg ctrl "$ctrl" --arg value "$value" \
                    '.controllers |=
                    map( if .mac_addr == $ctrl then .is_powered = $value end )' \
                    <<< "$bluetooth_info_json") ;;
                "Discoverable:") \
                    bluetooth_info_json=$(jq \
                    --arg ctrl "$ctrl" --arg value "$value" \
                    '.controllers |=
                    map( if .mac_addr == $ctrl then .is_discoverable = $value end )' \
                    <<< "$bluetooth_info_json") ;;
                "Pairable:") \
                    bluetooth_info_json=$(jq \
                    --arg ctrl "$ctrl" --arg value "$value" \
                    '.controllers |=
                    map( if .mac_addr == $ctrl then .is_pairable = $value end )' \
                    <<< "$bluetooth_info_json") ;;
                "Discovering:")  \
                    bluetooth_info_json=$(jq \
                    --arg ctrl "$ctrl" --arg value "$value" \
                    '.controllers |=
                    map( if .mac_addr == $ctrl then .is_discovering = $value end )' \
                    <<< "$bluetooth_info_json") ;;
                "*") true ;;
            esac
        done < <(bluetoothctl show "$ctrl")
    done
    # devices info
    # ---------------
    local dev name
    while read -r dev mac_addr name ; do 
        bluetooth_info_json="$(jq \
            --arg mac_addr "$mac_addr" \
            --arg name "$name" \
            '.devices += [{"mac_addr":$mac_addr,"name":$name}]' \
            <<< "$bluetooth_info_json" )"
    done < <(bluetoothctl devices)

    for dev in $(jq -r '.devices[].mac_addr' <<< "$bluetooth_info_json" ) ; do 
        while read -r key value ; do 
            case "$key" in 
                "Paired:") \
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    --arg value "$value" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .is_paired = $value end)' \
                    <<< "$bluetooth_info_json" ) ;;
                "Bonded:") \
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    --arg value "$value" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .is_bonded = $value end)' \
                    <<< "$bluetooth_info_json" ) ;;
                "Trusted:") \
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    --arg value "$value" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .is_trusted = $value end)' \
                    <<< "$bluetooth_info_json" ) ;;
                "Blocked:") \
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    --arg value "$value" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .is_blocked = $value end)' \
                    <<< "$bluetooth_info_json" ) ;;
                "Connected:") \
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    --arg value "$value" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .is_connected = $value end)' \
                    <<< "$bluetooth_info_json" ) ;;
                "Battery") 
                    value=${value##*'('} 
                    value=${value%%')'*} 
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    --arg value "$value" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .battery_perc = $value end)' \
                    <<< "$bluetooth_info_json" ) ;;
            esac
            case "$value" in 
                "Audio Sink"*|"Advanced Audio"*) \
                    bluetooth_info_json=$(jq \
                    --arg dev "$dev" \
                    '.devices |= 
                    map(if .mac_addr == $dev then .is_audio_device = "yes" else .is_audio_device = "no" end)' \
                    <<< "$bluetooth_info_json" ) ;;
            esac
        done < <( bluetoothctl info "$dev" )
    done

    jq -n --argjson bluetooth_info_json "$bluetooth_info_json" \
      '{"bt":$bluetooth_info_json}' 2> /dev/null || printf '{"bt":{}}'
}
# }}}

setup_cache_dir

get_gpu_main > "$CACHE_DIR/gpuinfo" 2> /dev/null &
disk_stats > "$CACHE_DIR/diskinfo" 2> /dev/null &
fetch_music > "$CACHE_DIR/musicinfo" 2> /dev/null &
fetch_volume > "$CACHE_DIR/volumeinfo" 2> /dev/null &
fetch_network > "$CACHE_DIR/netinfo" 2> /dev/null &
fetch_bluetooth > "$CACHE_DIR/btinfo" 2> /dev/null &

wait


OUTPUT="$( jq -n \
   --argjson gpu "$(< "$CACHE_DIR/gpuinfo")" \
   --argjson disk "$(< "$CACHE_DIR/diskinfo")" \
   --argjson music "$(< "$CACHE_DIR/musicinfo")" \
   --argjson volume "$(< "$CACHE_DIR/volumeinfo")" \
   --argjson net "$(< "$CACHE_DIR/netinfo")" \
   --argjson bt "$(< "$CACHE_DIR/btinfo")" \
   '$gpu + $disk + $music + $volume + $net + $bt' 2> /dev/null )"

[[ "$OUTPUT" ]] && printf '%s' "$OUTPUT" \
    > "$CACHE_DIR"/maximainit \
    2> /dev/null \
    || exit 1
[[ "$OUTPUT" ]] && printf '%s' "$OUTPUT" || exit 1
