#!/usr/bin/env bash

# Brightness
BRIGHTNESS="$(brightnessctl g 2> /dev/null || printf '"null"')" 
# Bluetooth
BT_DEVICES_CONNECTED=0
while read -r _device mac name ; do 
    : "$name" # Discard usused var
    while read -r key value ; do 
        [[ "$key" == "Connected:" && "$value" == "yes" ]] \
        && ((BT_DEVICES_CONNECTED++))
    done < <(bluetoothctl info "$mac" 2> /dev/null )
done < <(bluetoothctl devices 2> /dev/null )
# volume
read -r _volume VOL_SINK IS_MUTE_SINK \
    < <( wpctl get-volume @DEFAULT_SINK@ 2> /dev/null || printf '"null"' )
read -r _volume VOL_SOURCE IS_MUTE_SOURCE \
    < <( wpctl get-volume @DEFAULT_SOURCE@ 2> /dev/null || printf '"null"' )
[[ "$IS_MUTE_SINK" == '' ]] && IS_MUTE_SINK=false || IS_MUTE_SINK=true
[[ "$IS_MUTE_SOURCE" == '' ]] && IS_MUTE_SOURCE=false || IS_MUTE_SOURCE=true
[[ "$VOL_SINK" == '"null"' ]] && IS_MUTE_SINK='"null"'
[[ "$VOL_SOURCE" == '"null"' ]] && IS_MUTE_SOURCE='"null"'
# time
TIME="\"$(date "+%r||%a|%d/%m/%y|󰃭" 2> /dev/null || printf '"null"' )\""
# sway
SWAY_WP="$(swaymsg --raw -t get_workspaces 2> /dev/null || printf '"null"' )"
SWAY_BS="$(swaymsg --raw -t get_binding_state 2> /dev/null || printf '"null"' )"

scroll_text() {
    local text="$1"
    local width="$2"
    local len=${#text}

    if (( len <= width )); then
        printf "%s" "$text"
        return
    fi

    local spacer="   "
    local scroll="$text$spacer"

    local sec
    sec="$(date "+%s" 2> /dev/null)" 
    [[ "$sec" == '' ]] && sec=0

    local i="$((sec % ${#scroll}))"

    local part="${scroll:i:width}"
    if (( ${#part} < width )); then
        part+="${scroll:0:width-${#part}}"
    fi
    printf "%s" "${part} ..."
}
SWAY_FW="$(swaymsg -t get_tree | jq -r '
  recurse(.nodes[]?, .floating_nodes[]?)
  | select(.focused == true)
  | .name
' 2> /dev/null || printf "null")"
[[ "$SWAY_FW" == [[:digit:]]* ]] && SWAY_FW=''
SWAY_FW="\"$(scroll_text "$SWAY_FW" 50)\""

printf '
{
"brightness":%s,
"bt_devices_connected":%s,
"vol_sink":%s,
"vol_source":%s,
"is_mute_sink":%s,
"is_mute_source":%s,
"time":%s,
"sway_wp":%s,
"sway_bs":%s,
"sway_fw":%s
}
'\
    "$BRIGHTNESS" \
    "$BT_DEVICES_CONNECTED" \
    "$VOL_SINK" \
    "$VOL_SOURCE" \
    "$IS_MUTE_SINK" \
    "$IS_MUTE_SOURCE" \
    "$TIME" \
    "$SWAY_WP" \
    "$SWAY_BS" \
    "$SWAY_FW"
