music_directory    "{HOME}/Music"
playlist_directory "{ZAPP_PATH}/config/mpd/playlists"
db_file            "{ZAPP_PATH}/config/mpd/database"
log_file           "{ZAPP_PATH}/config/mpd/log"
pid_file           "{ZAPP_PATH}/config/mpd/pid"
state_file         "{ZAPP_PATH}/config/mpd/state"
sticker_file       "{ZAPP_PATH}/config/mpd/sticker.sql"

auto_update	"yes"

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}
audio_output {
  type "pipewire"
  name "PipeWire Sound Server"
}
